### PR TITLE
fix #94

### LINKED ISSUE #94: Enum with override members
Hi!

if in HelloWorld add next line
`TreeMap<String, String> map = new TreeMap<>();`
then you can see error
* What went wrong:
```
Execution failed for task ':debugHaxeCpp'.
> com.jtransc.error.InvalidOperationException: Can't find AstMethodRef(java.util.TreeMap$Bound$1,values,()[Ljava/util/TreeMap$Bound$1
```

In my project i have more errors with different Enums, i think it one problem, but i can not find solution.

If you can, please, help me.

### PR DESCRIPTION
**Pull request by SergeyLabutin**
Support enum with override members

### CODE REVIEW

File: jtransc-core/src/com/jtransc/plugin/enum/EnumJTranscPlugin.kt [hunk 1]
```diff
@@ -8,8 +8,9 @@ import com.jtransc.plugin.JTranscPlugin
  * Plugin that include values() method from enums
  */
 class EnumJTranscPlugin : JTranscPlugin() {
+	val enumName = "java.lang.Enum"
 	override fun onTreeShakingAddBasicClass(treeShaking: TreeShakingApi, fqname: FqName, oldclass: AstClass, newclass: AstClass) {
-		if (oldclass.modifiers.isEnum) {
+		if (oldclass.modifiers.isEnum && oldclass.extending.toString() == enumName) {
```
Comment (SergeyLabutin) [inline jtransc-core/src/com/jtransc/plugin/enum/EnumJTranscPlugin.kt]: Yes, this case. Tnx for test.
